# Site Settings
title: Georg Dües
tagline: Blogfolio
email: georg@duees.de
lang: de-DE
description: >
  This page is a blog and portfolio, made with Jekyll and GitHub pages websites
baseurl: "/"
url: "https://www.duees.de"
permalink: pretty
#favicon: /path/to/favicon.png
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Georg Dües
