# Site Settings
title: Georg Dües
tagline: Blog und Portfolio
email: georg@duees.de
lang: de-DE
description: >
  Persoenliche Website mit Blog und Portfolio zu IT Support, Linux, Training und Community.
baseurl: "/"
url: "https://www.duees.de"
permalink: pretty
#favicon: /path/to/favicon.png
remote_theme: georgduees/jekyll_minimal
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Georg Dües
