# Site Settings
title: Georg Dües
tagline: Blog and Portfolio
email: georg@duees.de
lang: en-US
description: >
  Personal website with a blog and portfolio about IT support, Linux, training, and community.
baseurl: "/"
url: "https://www.duees.de"
permalink: pretty
#favicon: /path/to/favicon.png
remote_theme: georgduees/jekyll_minimal
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Georg Dües
